name: coauthor-action
description: Generate a coauthor commit message
author: Kevin Zuniga Cuellar

branding:
  icon: 'heart'
  color: 'red'

inputs:
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    default: ${{ github.token }}

runs:
  using: node20
  main: dist/index.js