name: coauthor-action
description: Generate a coauthor commit message
author: Kevin Zuniga Cuellar

branding:
  icon: 'heart'
  color: 'red'

inputs:
  token:
    description: 'The GitHub token to use'
    required: true
  label:
    description: 'The label to trigger the action'
    default: 'add-coauthors'

runs:
  using: node20
  main: dist/index.js