name: Example Workflow

on:
  pull_request:
    types: [labeled]
    
jobs:
  generate-coauthor:
    name: Generate Coauthor
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Coauthor
        uses: kevinzunigacuellar/coauthor-action@main