name: Generate coauthors for a PR

permissions:
  pull-requests: write
  
on:
  issue_comment:
    types: [created]
    
jobs:
  generate-coauthor:
    name: Generate Coauthor
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Coauthor
        uses: ./