name: Generate coauthors for a PR

on:
  pull_request:
    types: [labeled]
    
jobs:
  generate-coauthor:
    name: Generate Coauthor
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Coauthor
        uses: ./