name: Generate coauthors for a PR

permissions:
  pull-requests: write
  
on:
  issue_comment:
    types: [created, edited, deleted]
    
jobs:
  generate-coauthor:
    name: Generate Coauthor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Coauthor
        uses: ./